name: Swap functional tests

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - develop
  pull_request:

jobs:
  job_functional_tests:
    uses: LedgerHQ/app-exchange/.github/workflows/reusable_swap_functional_tests.yml@polkadot-tests
    with:
      branch_for_polkadot: ${{ github.ref }}
